#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
RAG-Agent-XrayTestGenerator: Manual Test Importer
Imports JSON or CSV-formatted tests to Xray using REST API with proper custom fields
Works with tests generated by RAG-Agent-XrayTestGenerator

CSV format (semicolon-delimited):
  Test Case Identifier;Type;Summary;Action;Data;Expected Result;Test plan;Issue key;Test Set
  - Rows with the same Identifier belong to the same test case
  - Issue key column overrides USER_STORY_KEY from .env
"""

import sys
import os
import csv
import json
import requests
try:
    from dotenv import load_dotenv
except ImportError:
    def load_dotenv():
        return False

# Load environment variables from .env file
load_dotenv()

# Configuration from environment variables
JIRA_URL = os.getenv('JIRA_URL', 'https://portail.agir.orange.com')
JIRA_TOKEN = os.getenv('JIRA_TOKEN')
PROJECT_KEY = os.getenv('PROJECT_KEY', 'CTC2S')
USER_STORY_KEY = os.getenv('USER_STORY_KEY', 'CTC2S-234')
REVIEW_TRANSITION_ID = os.getenv('REVIEW_TRANSITION_ID', '').strip()
REVIEW_TRANSITION_NAME = os.getenv('REVIEW_TRANSITION_NAME', 'In Review').strip()

# Xray custom field IDs
TEST_TYPE_FIELD = "customfield_11209"
MANUAL_TEST_STEPS_FIELD = "customfield_11213"

headers = {
    "Authorization": f"Bearer {JIRA_TOKEN}",
    "Content-Type": "application/json"
}


def _require_token():
    if not JIRA_TOKEN:
        raise ValueError("ERROR: JIRA_TOKEN environment variable is not set. Please set it in your .env file or system environment variables.")


def _safe_response_snippet(response, limit=300):
    """Return a compact response snippet for logs without dumping full payloads."""
    try:
        body = response.text or ""
    except Exception:
        body = ""

    if len(body) <= limit:
        return body
    return f"{body[:limit]}..."


def build_manual_test_payload(test_case):
    """Build issue payload for a manual test in Xray format."""
    summary = test_case.get("name", "Test")
    description = test_case.get("description", "")
    steps = test_case.get("steps", [])
    result = test_case.get("result", "")

    xray_steps = []
    for step_idx, step_obj in enumerate(steps, 1):
        xray_steps.append({
            "index": step_idx,
            "fields": {
                "action": step_obj.get("step", ""),
                "data": "",
                "expected result": result
            }
        })

    return {
        "fields": {
            "project": {"key": PROJECT_KEY},
            "summary": summary,
            "description": description,
            "issuetype": {"name": "Test"},
            TEST_TYPE_FIELD: {"value": "Manual"},
            MANUAL_TEST_STEPS_FIELD: {"steps": xray_steps}
        }
    }


def create_manual_test(test_case):
    """Create a manual test with steps"""
    _require_token()
    payload = build_manual_test_payload(test_case)
    
    try:
        response = requests.post(
            f"{JIRA_URL}/rest/api/2/issue",
            json=payload,
            headers=headers,
            timeout=10
        )
        
        if response.status_code in [200, 201]:
            return response.json().get("key")
        else:
            snippet = _safe_response_snippet(response)
            print(f"[ERROR] Failed to create test: {response.status_code} {snippet}")
            return None
    except Exception as e:
        print(f"[ERROR] Exception: {str(e)}")
        return None


def resolve_transition_id(test_key):
    """Resolve transition ID using env override or transition name lookup."""
    _require_token()
    if REVIEW_TRANSITION_ID:
        return REVIEW_TRANSITION_ID

    try:
        response = requests.get(
            f"{JIRA_URL}/rest/api/2/issue/{test_key}/transitions",
            headers=headers,
            timeout=10
        )

        if response.status_code != 200:
            snippet = _safe_response_snippet(response)
            print(f"[WARN] Could not fetch transitions for {test_key}: {response.status_code} {snippet}")
            return None

        transitions = response.json().get("transitions", [])
        target_name = REVIEW_TRANSITION_NAME.lower()
        for transition in transitions:
            name = str(transition.get("name", "")).lower()
            if name == target_name:
                return transition.get("id")

        print(f"[WARN] Transition '{REVIEW_TRANSITION_NAME}' not found for {test_key}")
        return None
    except Exception as e:
        print(f"[WARN] Exception resolving transition for {test_key}: {str(e)}")
        return None


def transition_to_review(test_key):
    """Transition a test issue to review state."""
    transition_id = resolve_transition_id(test_key)
    if not transition_id:
        return False

    try:
        response = requests.post(
            f"{JIRA_URL}/rest/api/2/issue/{test_key}/transitions",
            json={"transition": {"id": str(transition_id)}},
            headers=headers,
            timeout=10
        )

        if response.status_code not in [200, 201, 204]:
            snippet = _safe_response_snippet(response)
            print(f"[WARN] Transition failed for {test_key}: {response.status_code} {snippet}")
            return False
        return True
    except Exception as e:
        print(f"[ERROR] Exception transitioning: {str(e)}")
        return False


def link_test_to_story(test_key, story_key):
    """Link test to user story"""
    _require_token()
    try:
        response = requests.post(
            f"{JIRA_URL}/rest/api/2/issueLink",
            json={
                "type": {"name": "Tests"},
                "inwardIssue": {"key": test_key},
                "outwardIssue": {"key": story_key}
            },
            headers=headers,
            timeout=10
        )
        if response.status_code not in [200, 201, 204]:
            snippet = _safe_response_snippet(response)
            print(f"[WARN] Linking failed for {test_key} -> {story_key}: {response.status_code} {snippet}")
            return False
        return True
    except Exception as e:
        print(f"[ERROR] Exception linking: {str(e)}")
        return False


def load_json(file_path):
    """Load test cases from a JSON file with per-test story key fallback."""
    with open(file_path, "r", encoding="utf-8") as f:
        test_cases = json.load(f)

    normalized = []
    for test_case in test_cases:
        case = dict(test_case)
        case["story_key"] = case.get("story_key") or case.get("issue_key") or USER_STORY_KEY
        normalized.append(case)
    return normalized


def load_csv(file_path):
    """
    Load test cases from a semicolon-delimited CSV file (Xray import format).
    Groups rows by 'Test Case Identifier'. Story key is read from 'Issue key' column.
    Returns a list of test cases, each with an explicit story_key.
    """
    test_cases = {}

    with open(file_path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f, delimiter=";")
        for row in reader:
            tc_id   = row.get("Test Case Identifier", "").strip()
            summary = row.get("Summary", "").strip()
            action  = row.get("Action", "").strip()
            result  = row.get("Expected Result", "").strip()
            ik      = row.get("Issue key", "").strip()

            if not tc_id:
                continue

            if tc_id not in test_cases:
                test_cases[tc_id] = {
                    "name": summary,
                    "description": summary,
                    "steps": [],
                    "result": result,
                    "story_key": ik or USER_STORY_KEY,
                }

            if ik and test_cases[tc_id]["story_key"] == USER_STORY_KEY:
                test_cases[tc_id]["story_key"] = ik

            # Update result from the first row that has one
            if result and not test_cases[tc_id]["result"]:
                test_cases[tc_id]["result"] = result

            if action:
                test_cases[tc_id]["steps"].append({"step": action})

    return list(test_cases.values())


def main(input_file):
    print("=" * 60)
    print("Manual Test Importer (JSON + CSV)")
    print("=" * 60)

    # Detect format and load
    try:
        ext = os.path.splitext(input_file)[1].lower()
        if ext == ".csv":
            print(f"[INFO] Format detected: CSV")
            test_cases = load_csv(input_file)
        else:
            print(f"[INFO] Format detected: JSON")
            test_cases = load_json(input_file)
    except Exception as e:
        print(f"[ERROR] Failed to load {input_file}: {str(e)}")
        return 1

    print(f"[INFO] Loaded {len(test_cases)} test cases from {input_file}")
    story_keys = sorted({case.get("story_key", USER_STORY_KEY) for case in test_cases})
    print(f"[INFO] Target User Story Keys: {', '.join(story_keys)}")

    # Import tests
    print(f"\n[INFO] Importing tests to Xray...")
    test_keys = []
    total_steps = 0

    for test_case in test_cases:
        steps = test_case.get("steps", [])
        total_steps += len(steps)
        story_key = test_case.get("story_key") or USER_STORY_KEY

        test_key = create_manual_test(test_case)
        if test_key:
            test_keys.append(test_key)
            print(f"  [OK] Created {test_key} with {len(steps)} steps")

            if transition_to_review(test_key):
                print(f"      [IN REVIEW] status updated")
            else:
                print(f"      [WARN] Failed to transition to review")

            if link_test_to_story(test_key, story_key):
                print(f"      [LINKED] to {story_key}")
            else:
                print(f"      [WARN] Failed to link")
        else:
            print(f"  [ERROR] Failed to create test")

    # Summary
    print("\n" + "=" * 60)
    print("IMPORT COMPLETE")
    print("=" * 60)
    print(f"Tests Created : {len(test_keys)}")
    if test_keys:
        print(f"Keys          : {', '.join(test_keys)}")
        print(f"Total Steps   : {total_steps}")
    print(f"Linked to     : {', '.join(story_keys)}")
    print(f"View          : {JIRA_URL}/browse/{PROJECT_KEY}")
    print("=" * 60)

    return 0 if test_keys else 1


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python import_manual_tests.py <file>")
        print("  JSON: python import_manual_tests.py output/manual_tests.json")
        print("  CSV:  python import_manual_tests.py output/manual_tests.csv")
        sys.exit(1)

    sys.exit(main(sys.argv[1]))
