#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
RAG-Agent-XrayTestGenerator: Cucumber Test Importer
Imports Cucumber/Gherkin feature files to Xray using REST API
Works with .feature files generated by RAG-Agent-XrayTestGenerator
"""

import sys
import os
import requests
try:
    from dotenv import load_dotenv
except ImportError:
    def load_dotenv():
        return False

# Load environment variables from .env file
load_dotenv()

# Configuration from environment variables
JIRA_URL = os.getenv('JIRA_URL', 'https://portail.agir.orange.com')
JIRA_TOKEN = os.getenv('JIRA_TOKEN')
PROJECT_KEY = os.getenv('PROJECT_KEY', 'CTC2S')
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()

headers = {
    "Authorization": f"Bearer {JIRA_TOKEN}"
}


def _is_debug_enabled():
    return LOG_LEVEL == "DEBUG"


def _debug(message):
    if _is_debug_enabled():
        print(f"[DEBUG] {message}")


def _safe_response_snippet(response, limit=300):
    """Return a compact response snippet for logs without dumping full payloads."""
    try:
        body = response.text or ""
    except Exception:
        body = ""

    if len(body) <= limit:
        return body
    return f"{body[:limit]}..."


def import_cucumber_feature(feature_file):
    """Import Cucumber feature file to Xray"""
    if not JIRA_TOKEN:
        print("[ERROR] JIRA_TOKEN environment variable is not set. Please set it in your .env file or system environment variables.")
        return []

    endpoint = f"{JIRA_URL}/rest/raven/2.0/import/feature?projectKey={PROJECT_KEY}"

    if not os.path.exists(feature_file):
        print(f"[ERROR] Feature file not found: {feature_file}")
        return []
    
    print(f"[INFO] Importing {feature_file} to Xray...")
    _debug(f"Endpoint: {endpoint}")
    
    try:
        # Use basename for the filename in multipart
        filename = os.path.basename(feature_file)
        with open(feature_file, "rb") as f:
            files = {"file": (filename, f, "multipart/form-data")}
            
            _debug(f"Sending file: {filename}")
            
            response = requests.post(
                endpoint,
                files=files,
                headers=headers,
                timeout=30
            )
            
            _debug(f"Response status: {response.status_code}")
            
            if response.status_code in [200, 201]:
                result = response.json()
                if isinstance(result, list):
                    test_keys = [item.get("key") for item in result]
                    print(f"[OK] Imported {len(test_keys)} Cucumber tests")
                    return test_keys
                else:
                    print(f"[WARN] Unexpected response format")
                    return []
            else:
                snippet = _safe_response_snippet(response)
                print(f"[ERROR] Import failed: {response.status_code} {snippet}")
                return []
    except Exception as e:
        print(f"[ERROR] Exception: {str(e)}")
        return []


def main(feature_file):
    print("=" * 60)
    print("Cucumber Test Importer")
    print("=" * 60)
    print()
    
    test_keys = import_cucumber_feature(feature_file)
    
    # Summary
    print("\n" + "=" * 60)
    print("IMPORT COMPLETE")
    print("=" * 60)
    print(f"Cucumber Tests Created: {len(test_keys)}")
    if test_keys:
        print(f"Keys: {', '.join(test_keys)}")
    print(f"View: {JIRA_URL}/browse/{PROJECT_KEY}")
    print("=" * 60)
    
    return 0 if test_keys else 1


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python import_cucumber_tests.py <feature_file>")
        print("Example: python import_cucumber_tests.py output/cucumber_tests.feature")
        sys.exit(1)
    
    sys.exit(main(sys.argv[1]))
